######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 26 10:43:17 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CFLAGS += -g

# Input
HEADERS += MainWindow.h kmc.h
SOURCES += main.cpp MainWindow.cpp
LIBS += -L. -lkmc
