######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 9 15:32:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . libkmc
INCLUDEPATH += .
CFLAGS += -g

# Input
HEADERS += kmc.h MainInterface.h MainWindow.h
SOURCES += main.cpp \
           MainInterface.cpp \
           MainWindow.cpp
RESOURCES += QtKMC.qrc

LIBS += -L. -lkmc


